language: python
python:
  - "3.5"
before_install:
  - "sudo apt-get update -qq"
install:
  - "sudo apt-get install -y intltool xmlto desktop-file-utils libcups2-dev"
  - "pip install pytest"
script: ./bootstrap && ./configure && make && make check && make distcheck
notifications:
  email: false
